//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quick_Planner.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Quick_Planner.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm.
        /// </summary>
        internal static string Alarm {
            get {
                return ResourceManager.GetString("Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archive Card.
        /// </summary>
        internal static string Archive_Card {
            get {
                return ResourceManager.GetString("Archive_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At.
        /// </summary>
        internal static string At {
            get {
                return ResourceManager.GetString("At", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue.
        /// </summary>
        internal static string Blue {
            get {
                return ResourceManager.GetString("Blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board.
        /// </summary>
        internal static string Board {
            get {
                return ResourceManager.GetString("Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlisted Cards.
        /// </summary>
        internal static string Cards_No_Owner {
            get {
                return ResourceManager.GetString("Cards_No_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel used to display notifications scheduled for your tasks.
        /// </summary>
        internal static string Channel_Description {
            get {
                return ResourceManager.GetString("Channel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task Notifications.
        /// </summary>
        internal static string Channel_Name {
            get {
                return ResourceManager.GetString("Channel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkmarks.
        /// </summary>
        internal static string Checkmarks {
            get {
                return ResourceManager.GetString("Checkmarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose List.
        /// </summary>
        internal static string Choose_List {
            get {
                return ResourceManager.GetString("Choose_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Board? (This cannot be undone).
        /// </summary>
        internal static string Confirmation_Board_Delete {
            get {
                return ResourceManager.GetString("Confirmation_Board_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Card?.
        /// </summary>
        internal static string Confirmation_Card_Delete {
            get {
                return ResourceManager.GetString("Confirmation_Card_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all cards? (this cannot be undone).
        /// </summary>
        internal static string Confirmation_Cards_Remove {
            get {
                return ResourceManager.GetString("Confirmation_Cards_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Label? (It will be removed from all cards).
        /// </summary>
        internal static string Confirmation_Label_Delete {
            get {
                return ResourceManager.GetString("Confirmation_Label_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove List? (All cards on this list will be moved to a board).
        /// </summary>
        internal static string Confirmation_List_Delete {
            get {
                return ResourceManager.GetString("Confirmation_List_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Field Must Contain Characters!.
        /// </summary>
        internal static string Empty_Title_Error {
            get {
                return ResourceManager.GetString("Empty_Title_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable.
        /// </summary>
        internal static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        internal static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labels.
        /// </summary>
        internal static string Labels {
            get {
                return ResourceManager.GetString("Labels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move all cards from this list.
        /// </summary>
        internal static string List_Move_Elements {
            get {
                return ResourceManager.GetString("List_Move_Elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Card.
        /// </summary>
        internal static string Move_Card {
            get {
                return ResourceManager.GetString("Move_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Board.
        /// </summary>
        internal static string New_Board {
            get {
                return ResourceManager.GetString("New_Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Card.
        /// </summary>
        internal static string New_Card {
            get {
                return ResourceManager.GetString("New_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Checkmark.
        /// </summary>
        internal static string New_Checkmark {
            get {
                return ResourceManager.GetString("New_Checkmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Label.
        /// </summary>
        internal static string New_Label {
            get {
                return ResourceManager.GetString("New_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New List.
        /// </summary>
        internal static string New_List {
            get {
                return ResourceManager.GetString("New_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string Notification {
            get {
                return ResourceManager.GetString("Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Scheduled.
        /// </summary>
        internal static string Notification_Scheduled {
            get {
                return ResourceManager.GetString("Notification_Scheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Time.
        /// </summary>
        internal static string Notification_Time {
            get {
                return ResourceManager.GetString("Notification_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Type.
        /// </summary>
        internal static string Notification_Type {
            get {
                return ResourceManager.GetString("Notification_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Type.
        /// </summary>
        internal static string Notification_Type_Temp {
            get {
                return ResourceManager.GetString("Notification_Type_Temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification has been canceled.
        /// </summary>
        internal static string Notification_UnScheduled {
            get {
                return ResourceManager.GetString("Notification_UnScheduled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification time cannot be earlier than current one!.
        /// </summary>
        internal static string NotificationTime_Error {
            get {
                return ResourceManager.GetString("NotificationTime_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification time cannot be later than task time.
        /// </summary>
        internal static string NotificationTime_Error2 {
            get {
                return ResourceManager.GetString("NotificationTime_Error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification cannot be scheduled due to insufficient permissions.
        /// </summary>
        internal static string Permission_Notification_Error {
            get {
                return ResourceManager.GetString("Permission_Notification_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        internal static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red.
        /// </summary>
        internal static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Board.
        /// </summary>
        internal static string Remove_Board {
            get {
                return ResourceManager.GetString("Remove_Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Card.
        /// </summary>
        internal static string Remove_Card {
            get {
                return ResourceManager.GetString("Remove_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all cards from the list.
        /// </summary>
        internal static string Remove_Cards {
            get {
                return ResourceManager.GetString("Remove_Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove List.
        /// </summary>
        internal static string Remove_List {
            get {
                return ResourceManager.GetString("Remove_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore Card.
        /// </summary>
        internal static string Restore_Card {
            get {
                return ResourceManager.GetString("Restore_Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Labels.
        /// </summary>
        internal static string Select_Labels {
            get {
                return ResourceManager.GetString("Select_Labels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Date.
        /// </summary>
        internal static string Set_Date {
            get {
                return ResourceManager.GetString("Set_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Due Date.
        /// </summary>
        internal static string Set_Due_Date {
            get {
                return ResourceManager.GetString("Set_Due_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Separate Notification Time.
        /// </summary>
        internal static string Set_Notification_Time {
            get {
                return ResourceManager.GetString("Set_Notification_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        internal static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time cannot be earlier than current one!.
        /// </summary>
        internal static string Time_Error {
            get {
                return ResourceManager.GetString("Time_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do this!.
        /// </summary>
        internal static string Title_Temp {
            get {
                return ResourceManager.GetString("Title_Temp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
